### ISSUE TITLE
Is the "Stake Honey" link meant to be in the nav bar of all out DAO pages?

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/gardens#135]
Just wondering if this was intentional. I don't think it's a big deal, it's pretty likely that anyone in the DAO will know what Honey is. 

![Screen Shot 2021-05-30 at 2 01 02 AM](https://user-images.githubusercontent.com/25679386/120093862-fb8af400-c0ea-11eb-8ca8-bfe68fa64869.png)

**Comment by rperez89** [comment]
cc @lkngtn @fioreb @0xGabi

**Comment by divine-comedian** [comment]
This confuses me actually - Stake Honey doesn't really tell me where the link goes and when I follow the link I'm not sure really what to do after that. 

I think I understand that I have to stake honey to interact with Celeste to become a Keeper or something like that, but only because I spent a good amount of time reading documentation on 1hive.. 

I might suggest to make this more explicitly clear by changing nav title to `Celeste` or `Become A Keeper`

**Comment by 0xGabi** [comment]
Good point @divine-comedian I agree with your feedback. I like the `Become A Keeper` wording. I wonder though if the navigation bar is the right place. Maybe as part of the FAQ, will be better.
