### ISSUE TITLE
Why grow a Garden

### ISSUE THREAD

**Issue by 0xmiel** [1Hive/gardens#7]
The idea here is that we have a document we can share with communities who may be interested in growing a Garden (perhaps housed in the Wiki?).

It’s true there are lots of great resources lying around: the forum is full of gems, Luke has published wonderful posts introducing both Celeste and Gardens,  and the Commons Stack has a pretty good post on conviction voting, but we don't seem to have a simple, self-contained overview of what these building blocks (Covenant/Gardens agreements, Celeste, Conviction voting) enable when used in combination, and how they improve on the status quo.

We should endeavour to explain as simply as possible:

- how a Garden agreement + Conviction voting + Celeste allow for more nuanced and complex governance, which in turn enables true DAOs (and why that matters)

- how a Garden agreement + Celeste ensure community values are upheld over the long-term (for example, by giving small holders the power to keep whales in check)

- how Conviction voting gives small holders the agency to contribute. And how it solves the problems associated with: governance attacks, low participation, and the overall inability to effectively prioritise and decide when there are many potential options all competing for consideration at once.

**Comment by GriffGreen** [comment]
Who is the audience?

#1 If the audience is outside of the crypto space... 

I would go high level and stay high level... no need to talk about CV at all... it is just the way.

The big theme is 

Economic models can work where business models don't... If your choice is collect donations or asking for volunteers... well you are pretty screwed... good luck begging for people to sacrifice.

If you can have business model and sell something... well starting an economy isn't as much of an improvement... You can probably seek investment for your company and create a revenue + ownership shares model. Ownership shares are effectively an economic model...

You can't issue shares very easily if you are just a community creating shared value.

You can create an economy tho... this is 10x better than all possible alternatives.

**Comment by sachayves** [comment]
I'd be very surprised if the first gardens were started by people outside of the crypto space.

I think the target audience at this stage is more teams in crypto that are thinking about governance and how best to move forward with either creating a DAO or upgrading their existing governance structure.

With respect to the latter, I've been talking with Julien from  [Unlock Protocol](https://github.com/unlock-protocol/unlock/wiki/Roadmap#decentralization-of-governance-unlock-dao), for example (hardly someone new to this space).


I think we have to do our best to challenge [the following assumption](https://twitter.com/ssaintleger/status/1383393094171643908) (image attached below) which has come up **a lot** since I posted my [essay](https://thewayofthedao.substack.com/p/daos-and-the-pitfalls-of-progressive) on the importance of community before product/market fit), so I'm afraid we're going to have to dig deep into the weeds a little bit.

In particular, we need to make it clear how Conviction voting ∪ Celeste ∪ Covenant ∪ Common Pool can result in more effective governance, and show people inside this space how a radically better world is possible.

![EzLLk1RVIAUsVFp](https://user-images.githubusercontent.com/5483559/115439398-d44d2700-a20e-11eb-8944-5e0484d1b9c3.jpg)

**Comment by GriffGreen** [comment]
Sorry i wanted to add the second section as well... I was writing it in other calls... so it was slow

**Comment by sachayves** [comment]
No worries!

I think comparing and contrasting with other options is a great idea.

**Comment by sachayves** [comment]
Rather than just docs, I'm now seeing this more as a series of blog posts.

Perhaps we can have two streams here. One on effective governance (where we explain the possibilities afforded by Conviction voting ∪ Celeste ∪ a Covenant ∪ a Common Pool)

And a second on comparing and contrasting with the options available, Compound, DAOStack, etc.

**Comment by 0xGabi** [comment]
Integrated in articles
